### ISSUE TITLE
Feature Request - Log the following events

### ISSUE THREAD

**Issue by Derpitron** [curtisf/logger#21]
- ~~Emojis~~ If I may ask, what exactly is broken about the emojis module?
- Log Profile Picture Changes - Opt in for administrators and members so it doesn't clog big servers and user's consent is respected
- Monitor stream start/stop, possibly with duration and quality/framerate
- Discord Audit Log seems to show who moved a user to a voice channel. Is this in the audit log API which the bot uses? if so, please add "who move who to what voice channel" feature
![image](https://user-images.githubusercontent.com/46134462/122178140-f2987180-cea3-11eb-88fd-5bada075d80f.png)

**Comment by SUPERCHIEFYT** [comment]
Who moved or disconnected a user from voice chat isn't possible for Logger due to it's size. (ratelimit issues) 
> Although that's in the [`Patron Logger`](https://patreon.com/Logger) bot due to it being smaller. 
------
The `guildEmojiUpdate` event was disabled due to it being buggy and not working properly iirc.

**Comment by curtisf** [comment]
Emojis are disabled because there kept on being a bug where the bot would spam emojis updated a ton. I need to rewrite it as well as guild update because it's behind. This will have to wait because I'm working full time and have very little motivation right now.

As for pfp logging, I had the chance to add user pfp logging awhile back and denied it because I don't want to store avatar hashes. Also, manually asking every user whether it's okay to log pfp changes is not worth it for the benefit it gives (nobody would allow it). A server administrator, upon inviting the bot, grants permission to log stuff from users so long as it's relevant to the operation of the bot. Bots like vortex log pfp changes already and don't even ask for permission.

Hope this helps

**Comment by curtisf** [comment]
Monitoring stream start/end and quality/bitrate is kinda niche and to this day I haven't heard anyone mention logging it. I'm not sure it's worth building the infrastructure for it (really just some redis keys). If you really want it, you should probably selfhost.

**Comment by Derpitron** [comment]
thanks for the prompt replies. for now, for pfp changes I will use the vortex bot. is there any bot which logs emojis?
